name: dbt CI

# トリガー
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dbt:
    # GitHubが用意したUbuntu上で下記を実行
    runs-on: ubuntu-latest

    steps:
      # GitHubからコードを持ってくる
      - name: Checkout
        uses: actions/checkout@v4

      # Python 3.13 を用意
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # dbt-bigquery をインストール
      - name: Install dbt
        run: |
          pip install dbt-bigquery

      # dbt --version 確認
      - name: Check dbt
        run: dbt --version